### ISSUE TITLE
Where is OpenIdConnect.Server package imported?

### ISSUE THREAD

**Issue by BrainCrumbz** [tim-cools/RealTimeWeb.NET#1]
Hello!

While browsing through code and in [related post](http://www.soloco.be/realtimeweb-react-authentication-on-asp-net-core/) we could not find any (`.json`) file where `AspNet.Security.OpenIdConnect.Server` package is actually imported. But then it is referenced everywhere with `using AspNet.Security.OpenIdConnect.Server;`.

What are we missing? Thank you

**Comment by tim-cools** [comment]
Hi @BrainCrumbz ,

Due to bugs I was a stuck with current (at that time) nuget version. It turned out that the libraries not yet stable and changing quit a lot. 

That is why I included the source code of several libraries in the solution. (see https://github.com/tim-cools/RealTimeWeb.NET/tree/master/src/Soloco.RealTimeWeb/Infrastructure/Temp) This is a bad practice :-) But it was the only way for me to continue working on the solution.

Because I also had many other problems (mainly bugs in Core and libraries) I put the project on hold until RC2. I will correct this and upgrade the whole project to .NET Core RC2 whenever it is released....

Hope this helps....

**Comment by BrainCrumbz** [comment]
Thanks for your reply. Yes, we also saw that RC2 state of the art is still unstable, and together with it go all libraries relying on that. At the moment we're sticking with RC1 libraries/dependencies.

**Comment by tim-cools** [comment]
I also tried that. But you might get stuck if the Authentication is what you after. Many bug are fixed after this RC1.

I hope we have a stable version soon...

**Comment by PinpointTownes** [comment]
FYI, `AspNet.Security.OpenIdConnect.Server` beta5-final was uploaded to NuGet.org yesterday.

Don't hesitate to ping me if you need help with the ASOS beta4 -> beta5 migration :shipit:

**Comment by tim-cools** [comment]
@PinpointTownes thanks for letting me know!! 

Converting the app to the latest bit (rc2 + dependencies) is high on my prio list, but first I need to complete a talk I give about Marten next Thursday. I will ping you as soon a I manage to update the example... ( Or not :-) )

**Comment by BrainCrumbz** [comment]
@PinpointTownes thanks for info
